//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20
.address_size 64

	// .globl	kernel          // -- Begin function kernel
                                        // @kernel
.visible .entry kernel(
	.param .u64 kernel_param_0
)
{
	.reg .f32 	%f<3>;
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<4>;

// %bb.0:                               // %entry
	ld.param.u64 	%rd1, [kernel_param_0];
	mov.u32 	%r1, %tid.x;
	mul.wide.s32 	%rd2, %r1, 4;
	add.s64 	%rd3, %rd1, %rd2;
	ld.global.f32 	%f1, [%rd3];
	add.rn.f32 	%f2, %f1, %f1;
	st.global.f32 	[%rd3], %f2;
	ret;
}
                                        // -- End function

